name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        ruby: ["2.5", "2.6", "2.7", "3.0"]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: StandardRb check
      run: bundle exec standardrb

    - name: Run tests
      run: |
        bundle exec rake test
